GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "A Verdade 2",
    "author": "Lucas Xisde",
    "url": "String",
    "likes": 108
}

###
DELETE http://localhost:3003/api/blogs/5eacc3f21657b0371c9cc926

###
PUT http://localhost:3003/api/blogs/5eacc3e01657b0371c9cc925
Content-Type: application/json

{
    "likes": 10
}

###

GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Fel",
    "name": "xfelipecg",
    "password": "123456"
}

###
DELETE http://localhost:3003/api/users/5eb0c5dd58ebfe4508ab3cc3
