GET http://localhost:3001/api/persons/

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Felipe",
    "number": "108108"
}

###

DELETE http://localhost:3001/api/persons/5ea7717cbc0d011d405314dc

###
PUT http://localhost:3001/api/persons/5ea7706dc42f7e0ddccf4531
Content-Type: application/json

{
    "number": "54"
}